version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: security_db
    restart: always
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
