services:
  db:
    container_name: pietnasty_lipiec25
    image: postgres:latest
    environment:
      POSTGRES_USER: pietnasty_lipiec25
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:


