### GET request to example server
GET http://localhost:8080/api

###

POST http://localhost:8080/api
Content-Type: application/json

{
  "firstName": "Raman",
  "age": 21
}

###

DELETE http://localhost:8080/api/2

###

GET http://localhost:8080/api/5
