###
GET http://localhost:8080/students

###

GET localhost:8080/students/last_name/Binga

###

GET localhost:8080/students/by-last-name?lastName=Barcik

###

GET localhost:8080/students/sort?direction=desc

###
###       EXAMPLES FOR PAGING
###GET /students/page?page=1&size=7
###GET /students/page?sort=email,desc
###GET /students/page?sort=firstName,asc&sort=age,desc

GET localhost:8080/students/page?page=1&size=99,sort=age

###

GET localhost:8080/students/count?age=21

###


POST http://localhost:8080/students
Content-Type: application/json

{
  "email": "11.abaab0@l.com",
  "age": 82,
  "firstName": "12223",
  "lastName": "Igoarao"
}


###

DELETE localhost:8080/students/9
Content-Type: application/json

###
DELETE localhost:8080/students/by-age?age=12

###

PUT localhost:8080/students/1
Content-Type: application/json

{
  "email": "11.baab0@l.com",
  "age": 82,
  "firstName": "12223",
  "lastName": "Igorao"
}


###

GET localhost:8080/student-id-card

###

POST http://localhost:8080/student-id-card
Content-Type: application/json

{
  "cardNumber": "CARD-001",
  "student": {
    "id": 1
  }
}


###

GET localhost:8080/books

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "bookName": "Hobbit",
  "student": {
    "id": 1
  }
}


###

GET localhost:8080/books/find-student-by-book/Hobbit


###

GET localhost:8080/books


###
GET localhost:8080/courses